name: devsecops-application-cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Set up Maven
          uses: stCarolas/setup-maven@v4.5
          with:
            maven-version: 3.8.2
    
        - name: Build and Test
          if: always()
          run: mvn -B package --file pom.xml
          continue-on-error: true

        - name: Upload Report
          uses: 'actions/upload-artifact@v3'
          with:
            name: jacoco-report
            path: |
              ${{ github.workspace }}/target/site/jacoco/jacoco.xml
              ${{ github.workspace }}/target/site/jacoco/index.html

        - name: Add coverage to PR
          id: jacoco
          uses: madrapps/jacoco-report@v1.6.1
          with:
            paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 80
            min-coverage-changed-files: 60
            title: '# :recycle: Coverage Report'
            update-comment: true
            pass-emoji: ':green_circle:'
            fail-emoji: ':red_circle:'